apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-server-ingress
{{- if eq .Values.tlsEnabled true }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/enable-cors: 'true'
{{ end }}
spec:
{{- if eq .Values.tlsEnabled true }}
  tls:
  - hosts:
      - {{ .Values.hostName }}
    secretName: demoapp-secret
{{ end }}
  rules:
  - host: {{ .Values.hostName }}
    http:
      paths:
      - pathType: Prefix
        path: /movies-api
        backend:
            service: 
                name: "movie-api"
                port:
                   number: 8080
      - pathType: Prefix
        path: /
        backend:
            service: 
                name: "movie-ui"
                port:
                  number: 80
      - pathType: Prefix
        path: /auth
        backend:
            service: 
                name: "keycloak"
                port:
                  number: 80

            
