apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-ui
  labels:
    app: movie-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-ui
  template:
    metadata:
      labels:
        app: movie-ui
    spec:
      containers:
        - name: smx
          image: modeseven/reactfrontend:{{ .Values.uiImageTag }}
          ports:
            - containerPort: 80
          env:
          - name: KEYCLOAK_HOST
            value: {{ .Values.keycloakHost }}
---
apiVersion: v1
kind: Service
metadata:
  name: movie-ui
spec:
  selector:
    app: movie-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-api
  labels:
    app: movie-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-api
  template:
    metadata:
      labels:
        app: movie-api
    spec:
      containers:
        - name: movie-api
          image: modeseven/mongobackend:{{ .Values.apiImageTag }}
          ports:
            - containerPort: 8080
          env:
          - name: MONGODB_HOST
            value: {{ .Values.mongoHost }}
          - name: MONGODB_PORT
            value: {{ quote .Values.mongoPort }}
          - name: KEYCLOAK_HOST
            value: {{ .Values.keycloakHost }}
          - name: SERVER_SERVLET_CONTEXT-PATH
            value: "/movies-api"
---
apiVersion: v1
kind: Service
metadata:
  name: movie-api
spec:
  selector:
    app: movie-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080



            