apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: {{ .Values.keycloakImage }}
          ports:
            - containerPort: 8080
            - containerPort: 9900
          env:
          - name: KEYCLOAK_USER
            value: admin
          - name: KEYCLOAK_PASSWORD
            value: admin
          - name: DB_VENDOR
            value: mysql
          - name: DB_ADDR
            value: mysql
          - name: DB_USER
            value: keycloak
          - name: DB_PASSWORD
            value: password
          - name: JDBC_PARAMS
            value: useSSL=false
          - name: PROXY_ADDRESS_FORWARDING
            value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080