## https://www.cloudytuts.com/guides/kubernetes/how-to-deploy-mongodb-on-kubernetes/
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: {{ .Values.mongoImage }}
        ports:
          - containerPort: 27017
        livenessProbe:
          exec:
            command:
              - mongo
              - --disableImplicitSessions
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 8
          failureThreshold: 2
        readinessProbe:
          exec:
            command:
              - mongo
              - --disableImplicitSessions
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 8
          failureThreshold: 2
{{- if eq .Values.persistence.enabled true }}
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: "mongo-{{ .Values.env }}"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "mongo-{{ .Values.env }}"
  labels:
    type: "local"
spec:
  storageClassName: "local"
  capacity:
    storage: "5Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/{{ .Values.rootVolumeFolder }}/{{ .Release.Name }}-{{ .Values.env }}/mongo-{{ .Values.env }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "mongo-{{ .Values.env }}"
spec:
  volumeName: "mongo-{{ .Values.env }}"
  storageClassName: "local"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
{{ end }}