apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-api
  labels:
    app: movie-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-api
  template:
    metadata:
      labels:
        app: movie-api
    spec:
      initContainers:
      - name: init-check-keycloak
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup keycloak; do echo waiting for keycloak; sleep 15; done;']
      containers:
        - name: movie-api
          image: modeseven/movietalk-api:{{ .Values.apiImageTag }}
          readinessProbe:
            httpGet:
              path: /movies-api/actuator/health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 8
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /movies-api/actuator/health
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 8
            failureThreshold: 2
          ports:
            - containerPort: 8080
          env:
          - name: MONGODB_HOST
            value: {{ .Values.mongoHost }}
          - name: MONGODB_PORT
            value: {{ quote .Values.mongoPort }}
          - name: KEYCLOAK_HOST
            value: {{ .Values.tlsEnabled | ternary "https" "http" }}://{{ .Values.hostName }}
          - name: SERVER_SERVLET_CONTEXT-PATH
            value: "/movies-api"
---
apiVersion: v1
kind: Service
metadata:
  name: movie-api
spec:
  selector:
    app: movie-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
